FrameworkRepositoryGenerico.WebCore/Controllers/AnoController.cs
using FrameworkRepositoryGenerico.DataBase.Entidades;
using FrameworkRepositoryGenerico.WebCore.Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace FrameworkRepositoryGenerico.WebCore.Controllers
{
    public class AnoController : Controller 
    {
        BaseApi _anoApi = new BaseApi();
        private readonly string _UrlAno = "api/Ano/";

        public async Task<IActionResult> Index() {
            List<Ano> _ano = new List<Ano>();
            HttpClient client = _anoApi.Initial();
            var url = _UrlAno;
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _ano = JsonConvert.DeserializeObject<List<Ano>>(result);
            }

            TempData["mensagem"] = "Mensagem de sucesso";

            return View(_ano);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] Ano ano)
        {

            var url = _UrlAno + "Cadastrar";
            HttpClient client = _anoApi.Initial();
            var serializedAno = JsonConvert.SerializeObject(ano);
            var content = new StringContent(serializedAno, Encoding.UTF8, "application/json");
            var res = await client.PostAsync(url,content);

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var url = _UrlAno + id;
            Ano _ano = new Ano();
            HttpClient client = _anoApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _ano = JsonConvert.DeserializeObject<Ano>(result);
                
            }
            return View(_ano);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind] Ano ano)
        {
            if (ModelState.IsValid)
            {
                var url = _UrlAno + "Cadastrar";
                HttpClient client = _anoApi.Initial();
                var serializedAno = JsonConvert.SerializeObject(ano);
                var content = new StringContent(serializedAno, Encoding.UTF8, "application/json");
                var res = await client.PostAsync(url, content);
                if (res.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Index");
                }
            }
            return View(ano);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var url = _UrlAno + id;
            Ano _ano = new Ano();
            HttpClient client = _anoApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _ano = JsonConvert.DeserializeObject<Ano>(result);

            }
            return View(_ano);
            
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            string url = _anoApi.UriApi() + _UrlAno + id;

            using (var httpClient = new HttpClient())
            {
                    var res = await httpClient.DeleteAsync(url);
                   
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }

            }
            return RedirectToAction("Index");
            

        }
    }
}

FrameworkRepositoryGenerico.WebCore/Controllers/ClienteController.cs
using System.Net.Http;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FrameworkRepositoryGenerico.WebCore.Helper;
using FrameworkRepositoryGenerico.DataBase.Entidades;
using Newtonsoft.Json;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using System;

namespace FrameworkRepositoryGenerico.WebCore.Controllers
{
    public class ClienteController : Controller
    {
        
        private readonly string _UrlCliente = "api/Cliente/";
        private readonly string _UrlTipoCliente = "api/TipoCliente/";


        BaseApi _clienteApi = new BaseApi();

        public async Task<IActionResult> Index()
        {
            List<Cliente> _Cliente = new List<Cliente>();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(_UrlCliente);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _Cliente = JsonConvert.DeserializeObject<List<Cliente>>(result);
            }
            return View(_Cliente);
        }

        public IActionResult Pesquisar()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Pesquisar([Bind("Nome")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {

                var url = _UrlCliente + cliente.Nome;
                List<Cliente> _Cliente = new List<Cliente>();
                HttpClient client = _clienteApi.Initial();
                HttpResponseMessage res = await client.GetAsync(url);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    _Cliente = JsonConvert.DeserializeObject<List<Cliente>>(result);
                }
                
            }
            return View(cliente);
        }

        public async Task<IActionResult> IndexCliente(int? id)
        {
            var url = _UrlCliente + id;
            Cliente _Cliente = new Cliente();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _Cliente = JsonConvert.DeserializeObject<Cliente>(result);
            }
            return View(_Cliente);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            List<TipoCliente> ListaTipoCliente = await ListarTipoCliente();
            ViewData["TipoClienteId"] = new SelectList(ListaTipoCliente, "Id", "Descricao");
            return View();
        }

        public async Task<List<TipoCliente>> ListarTipoCliente()
        {
            List<TipoCliente> _TipoCliente = new List<TipoCliente>();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(_UrlTipoCliente);
            if (res.IsSuccessStatusCode)
            {
                res.Content.Headers.ContentLength = 11987;
                var result = res.Content.ReadAsStringAsync().Result;
                _TipoCliente = JsonConvert.DeserializeObject<List<TipoCliente>>(result);
            }
            return _TipoCliente.ToList();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cpf_Cnpj,TipoClienteId,Ativo")] Cliente cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var url = _UrlCliente + "Cadastrar";
                    HttpClient client = _clienteApi.Initial();
                    var serializedCategoria = JsonConvert.SerializeObject(cliente);
                    var content = new StringContent(serializedCategoria, Encoding.UTF8, "application/json");
                    var res = await client.PostAsync(url, content);
                    return Created(_UrlCliente, cliente);

                    //return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                return BadRequest($"Erro: {ex.ToString()}");
            }
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {

            List<TipoCliente> ListaTipoCliente = await ListarTipoCliente();
            ViewData["TipoClienteId"] = new SelectList(ListaTipoCliente, "Id", "Descricao");

            var url = _UrlCliente + id;
            Cliente _cliente = new Cliente();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _cliente = JsonConvert.DeserializeObject<Cliente>(result);

            }
            return View(_cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                var url = _UrlCliente + "Cadastrar";
                HttpClient client = _clienteApi.Initial();
                var serializedCategoria = JsonConvert.SerializeObject(cliente);
                var content = new StringContent(serializedCategoria, Encoding.UTF8, "application/json");
                var res = await client.PostAsync(url, content);
                if (res.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Index");
                }
            }
            return View(cliente);
        }
    }
}

FrameworkRepositoryGenerico.WebCore/Controllers/RegraController.cs
using FrameworkRepositoryGenerico.DataBase.Entidades;
using FrameworkRepositoryGenerico.WebCore.Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace FrameworkRepositoryGenerico.WebCore.Controllers
{
    public class RegraController : Controller 
    {
        BaseApi _regraApi = new BaseApi();
        private readonly string _UrlRegra = "api/Regra/";

        public async Task<IActionResult> Index() {
            List<Regra> _regra = new List<Regra>();
            HttpClient client = _regraApi.Initial();
            var url = _UrlRegra;
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _regra = JsonConvert.DeserializeObject<List<Regra>>(result);
            }

            TempData["mensagem"] = "Mensagem de sucesso";

            return View(_regra);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] Regra regra)
        {

            var url = _UrlRegra + "Cadastrar";
            HttpClient client = _regraApi.Initial();
            var serializedRegra = JsonConvert.SerializeObject(regra);
            var content = new StringContent(serializedRegra, Encoding.UTF8, "application/json");
            var res = await client.PostAsync(url,content);

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            var url = _UrlRegra + id;
            Regra _regra = new Regra();
            HttpClient client = _regraApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _regra = JsonConvert.DeserializeObject<Regra>(result);
                
            }
            return View(_regra);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind] Regra regra)
        {
            if (ModelState.IsValid)
            {
                var url = _UrlRegra + "Cadastrar";
                HttpClient client = _regraApi.Initial();
                var serializedRegra = JsonConvert.SerializeObject(regra);
                var content = new StringContent(serializedRegra, Encoding.UTF8, "application/json");
                var res = await client.PostAsync(url, content);
                if (res.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Index");
                }
            }
            return View(regra);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var url = _UrlRegra + id;
            Regra _regra = new Regra();
            HttpClient client = _regraApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _regra = JsonConvert.DeserializeObject<Regra>(result);

            }
            return View(_regra);
            
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            string url = _regraApi.UriApi() + _UrlRegra + id;

            using (var httpClient = new HttpClient())
            {
                var res = await httpClient.DeleteAsync(url);

                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }

            }
            return RedirectToAction("Index");
        }
    }
}

FrameworkRepositoryGenerico.WebCore/Views/Shared/Mensagem.cshtml
<div>
    @TempData["mensagem"]
</div>

FrameworkRepositoryGenerico.WebCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrameworkRepositoryGenerico.WebCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BackOffice</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fabricante" asp-action="Index">Fabricante</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Montadora" asp-action="Index">Montadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ano" asp-action="Index">Ano</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoCliente" asp-action="Index">Tipo de cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoContato" asp-action="Index">Tipo de contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoProduto" asp-action="Index">Tipo de produto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Regra" asp-action="Index">Regra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Pesquisar">Cliente</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - FrameworkRepositoryGenerico.WebCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>