FrameworkRepositoryGenerico.WebCore/Controllers/ClienteController.cs
using System.Net.Http;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FrameworkRepositoryGenerico.WebCore.Helper;
using FrameworkRepositoryGenerico.DataBase.Entidades;
using Newtonsoft.Json;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using System;

namespace FrameworkRepositoryGenerico.WebCore.Controllers
{
    public class ClienteController : Controller
    {
        
        private readonly string _UrlCliente = "api/Cliente/";
        private readonly string _UrlTipoCliente = "api/TipoCliente/";


        BaseApi _clienteApi = new BaseApi();

        public async Task<IActionResult> Index()
        {
            List<Cliente> _Cliente = new List<Cliente>();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(_UrlCliente);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _Cliente = JsonConvert.DeserializeObject<List<Cliente>>(result);
            }
            return View(_Cliente);
        }

        public IActionResult Pesquisar()
        {
            
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Pesquisar([Bind("Nome")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {

                var url = _UrlCliente + cliente.Nome;
                List<Cliente> _Cliente = new List<Cliente>();
                HttpClient client = _clienteApi.Initial();
                HttpResponseMessage res = await client.GetAsync(url);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    _Cliente = JsonConvert.DeserializeObject<List<Cliente>>(result);
                }
                
            }
            return View(cliente);
        }

        public async Task<IActionResult> IndexCliente(int? id)
        {
            var url = _UrlCliente + id;
            Cliente _Cliente = new Cliente();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _Cliente = JsonConvert.DeserializeObject<Cliente>(result);
            }
            return View(_Cliente);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            List<TipoCliente> ListaTipoCliente = await ListarTipoCliente();
            ViewData["TipoClienteId"] = new SelectList(ListaTipoCliente, "Id", "Descricao");
            return View();
        }

        public async Task<List<TipoCliente>> ListarTipoCliente()
        {
            List<TipoCliente> _TipoCliente = new List<TipoCliente>();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(_UrlTipoCliente);
            if (res.IsSuccessStatusCode)
            {
                res.Content.Headers.ContentLength = 11987;
                var result = res.Content.ReadAsStringAsync().Result;
                _TipoCliente = JsonConvert.DeserializeObject<List<TipoCliente>>(result);
            }
            return _TipoCliente.ToList();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cpf_Cnpj,TipoClienteId,Ativo")] Cliente cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var url = _UrlCliente + "Cadastrar";
                    HttpClient client = _clienteApi.Initial();
                    var serializedCategoria = JsonConvert.SerializeObject(cliente);
                    var content = new StringContent(serializedCategoria, Encoding.UTF8, "application/json");
                    var res = await client.PostAsync(url, content);
                    return Created(_UrlCliente, cliente);

                    //return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                return BadRequest($"Erro: {ex.ToString()}");
            }
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {

            List<TipoCliente> ListaTipoCliente = await ListarTipoCliente();
            ViewData["TipoClienteId"] = new SelectList(ListaTipoCliente, "Id", "Descricao");

            var url = _UrlCliente + id;
            Cliente _cliente = new Cliente();
            HttpClient client = _clienteApi.Initial();
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _cliente = JsonConvert.DeserializeObject<Cliente>(result);

            }
            return View(_cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                var url = _UrlCliente + "Cadastrar";
                HttpClient client = _clienteApi.Initial();
                var serializedCategoria = JsonConvert.SerializeObject(cliente);
                var content = new StringContent(serializedCategoria, Encoding.UTF8, "application/json");
                var res = await client.PostAsync(url, content);
                if (res.IsSuccessStatusCode)
                {
                    //return RedirectToAction("Index");
                }
            }
            return View(cliente);
        }
    }
}

FrameworkRepositoryGenerico.WebCore/Controllers/EnderecoController.cs
using FrameworkRepositoryGenerico.DataBase.Entidades;
using FrameworkRepositoryGenerico.WebCore.Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace FrameworkRepositoryGenerico.WebCore.Controllers
{
    public class EnderecoController : Controller
    {

        BaseApi _enderecoApi = new BaseApi();
        private readonly string _UrlEndereco = "api/Endereco/";
        private readonly string _UrlCliente = "api/Cliente/";

        [HttpGet]
        public async Task<IActionResult> Index(int? ClienteId)
        {
            Cliente _cliente = new Cliente();
            HttpClient client = _enderecoApi.Initial();
            var url = _UrlCliente + ClienteId;
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _cliente = JsonConvert.DeserializeObject<Cliente>(result);
            }
            return View(_cliente);
        }


        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            Cliente _Cliente = await GetCliente(id);
            ViewBag.Cliente = _Cliente;
            return View();
        }

        public async Task<Cliente> GetCliente(int? id)
        {
            Cliente _Cliente = new Cliente();
            HttpClient client = _enderecoApi.Initial();
            var url = _UrlCliente + id;
            HttpResponseMessage res = await client.GetAsync(url);
            if (res.IsSuccessStatusCode)
            {
                var result = res.Content.ReadAsStringAsync().Result;
                _Cliente = JsonConvert.DeserializeObject<Cliente>(result);
            }
            return _Cliente;

        }
    }
}

FrameworkRepositoryGenerico.WebCore/Views/Cliente/Create.cshtml
@model FrameworkRepositoryGenerico.DataBase.Entidades.Cliente
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Criar Cliente</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="TipoClienteId" class="control-label"></label>
                <select asp-for="TipoClienteId" class="form-control" asp-items="ViewBag.TipoClienteId"></select>
                

            </div>
            <div class="form-group">
                <label asp-for="Cpf_Cnpj" class="control-label"></label>
                <input asp-for="Cpf_Cnpj" class="form-control" />
                <span asp-validation-for="Cpf_Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Ativo" class="control-label"></label>
                <br />

                <input type="radio" asp-for="Ativo" value="true"><label asp-for="Ativo" class="control-label">Sim</label>
                <input type="radio" asp-for="Ativo" value="false"><label asp-for="Ativo" class="control-label">Não</label>

                <span asp-validation-for="Ativo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
</form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar para Lista</a>
</div>

<script type="text/javascript">

    $(document).ready(function () {
      
    });
        



</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrameworkRepositoryGenerico.WebCore/Views/Cliente/Edit.cshtml
@model FrameworkRepositoryGenerico.DataBase.Entidades.Cliente
@{
    ViewData["Title"] = "Edit";
}
<br />
<h2>Alterar Cliente</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TipoClienteId" class="control-label"></label>
                <select asp-for="TipoClienteId" class="form-control" asp-items="ViewBag.TipoClienteId"></select>


            </div>
            <div class="form-group">
                <label asp-for="Cpf_Cnpj" class="control-label"></label>
                <input asp-for="Cpf_Cnpj" class="form-control" />
                <span asp-validation-for="Cpf_Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Ativo" class="control-label"></label>
                <br />

                <input type="radio" asp-for="Ativo" value="true"><label asp-for="Ativo" class="control-label">Sim</label>
                <input type="radio" asp-for="Ativo" value="false"><label asp-for="Ativo" class="control-label">Não</label>

                <span asp-validation-for="Ativo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar para Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrameworkRepositoryGenerico.WebCore/Views/Cliente/Index.cshtml
@model IEnumerable<FrameworkRepositoryGenerico.DataBase.Entidades.Cliente>

    @{
        ViewData["Title"] = "Index";
    }

    <h1>Index</h1>

    <p>
        <a asp-action="Create">Criar Cliente</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cpf_Cnpj)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ativo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoCliente)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cpf_Cnpj)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoCliente.Descricao)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    <a href="@Url.Action("Index", "Endereco",new { id=item.Id }) )">Details</a>
                    @Html.ActionLink("Endereço", "Index", new { Controller = "Endereco", action = "Index", ClienteId = item.Id })
                    @Html.ActionLink("Edit", "Edit", "Endereco", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
            }
        </tbody>
    </table>

FrameworkRepositoryGenerico.WebCore/Views/Cliente/IndexCliente.cshtml
@model FrameworkRepositoryGenerico.DataBase.Entidades.Cliente

    @{
        ViewData["Title"] = "Index";
    }

   

    <p>
        <a asp-action="Create">Criar Cliente</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cpf_Cnpj)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ativo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoCliente)
                </th>
            </tr>
        </thead>
        <tbody>
           <tr>
                <td>
                    @Html.DisplayFor(model => model.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Nome)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Cpf_Cnpj)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Ativo)
                </td>
                <td>
                    @Html.DisplayFor(model => model.TipoCliente.Descricao)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                    @Html.ActionLink("Endereço", "Index", new { Controller = "Endereco", action = "Index", ClienteId = Model.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
                </td>
            </tr>
           
        </tbody>
    </table>

FrameworkRepositoryGenerico.WebCore/Views/Cliente/Pesquisar.cshtml
@model FrameworkRepositoryGenerico.DataBase.Entidades.Cliente
@{
    ViewData["Title"] = "Pesquisa";
}

<h1>Pesquisa</h1>


<table class="table">
    <form asp-action="Pesquisar">
        <label asp-for="Nome" class="control-label"></label>
        <input asp-for="Nome" class="form-control" />
        <input type="submit" value="Pesquisar" class="btn btn-default" />
    </form>
   
</table>